version: 2.1
orbs:
  golangci-lint: neilisaac/golangci-lint@0.0.1
  go: circleci/go@1.3.0
jobs:
  test:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - golangci-lint/lint
      - go/test:
          covermode: atomic
          failfast: true
          race: true
workflows:
  build:
    jobs:
      - test
